### ISSUE TITLE
Will Megatron-DeepSpeed rebase from https://github.com/NVIDIA/Megatron-LM in the future?

### ISSUE THREAD

**Issue by delock** [microsoft/Megatron-DeepSpeed#105]
Hi, I noticed that this repo had forked from https://github.com/NVIDIA/Megatron-LM and is around 800 commits behind.  There are new features keeping adding to Megatron-LM i.e. flash attention and sequence parallel.  Wonder whether there is plan in Megatron-DeepSpeed to keep up with Megatron-LM repo?   Thanks!

**Comment by jiayulu** [comment]
I was about to post the same question, any plans to merge in newer commits from upstream? I did a manual merge but there's just way too many conflicts.

**Comment by conglongli** [comment]
@delock @jiayulu We are planning to revise our examples including those in Megatron-DeepSpeed, but we have not finalized the plan yet. Because of that, there is no planned rebase in near future.

**Comment by delock** [comment]
Thanks for clarification @conglongli

**Comment by delock** [comment]
@conglongli is there any update of the plan?    In particular about plan for flash attention.  Does Megatron-DeepSpeed plan to support flash attention training from picking from Megatron-LM, or plan to support through DeepSpeed op builder?

**Comment by conglongli** [comment]
@delock We had an internal discussion about your interest on fast attention (this is less related to Megatron-DeepSpeed plan), and my colleague Tunji @tjruwase would like to talk to you to learn more about this. Could you contact him next week? I guess you already have his contact. Thanks.

**Comment by conglongli** [comment]
@delock @jiayulu We have just synced with Megatron-LM and merged 1100+ commits. Please take a look at the new main branch. We actually replaced the main branch by renaming branches, so you might have to clone the repo again because it's a bit tricky to update local repo that already cloned https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/managing-branches-in-your-repository/renaming-a-branch#updating-a-local-clone-after-a-branch-name-changes. There could still exist bugs, and we very welcome bug report/bug fix contributions.
