### ISSUE TITLE
Try to understand potential issues of merging all file into one *.bin (*.idx) file 

### ISSUE THREAD

**Issue by weiwchu** [microsoft/Megatron-DeepSpeed#143]
@conglongli or other Megatron-DeepSpeed authors,

I wonder if you can help me to understand the potential issues of [merging the 30 pile *.zst files  into a very large file for training](https://github.com/microsoft/Megatron-DeepSpeed/blob/1f640c00c115eee9cd8515db80f8c92a4c24e9ca/examples/data_efficiency/bert/pile_data_download_preprocess.py#L101).

Here are my understand (correct me if I were wrong):
I understand you want to have [a single index file](https://github.com/microsoft/Megatron-DeepSpeed/blob/1f640c00c115eee9cd8515db80f8c92a4c24e9ca/megatron/data/indexed_dataset.py#L422), so Megatron-DeepSpeed can know where the data is stored by accessing this single index file.

**But, is there any issue with storing this huge single data (*.bin) file on disk or cloud?** It could be over 10TB. 

If there is **any reference explaining the data-storge-and-access architecture of the Megatron-DeepSpeed**, can you share that with me?

Thank you very much.

**Comment by conglongli** [comment]
> But, is there any issue with storing this huge single data (*.bin) file on disk or cloud? It could be over 10TB.

We won't be able to answer "how to store data with size X" because that really depends on what hardware environment you have. It's better to consult your cluster admin or cloud storage provider.

On the other hand, at the same comment you pointed to https://github.com/microsoft/Megatron-DeepSpeed/blob/1f640c00c115eee9cd8515db80f8c92a4c24e9ca/examples/data_efficiency/bert/pile_data_download_preprocess.py#L103, I actually left a comment that it's not required to merge all data file into a single file, because Megatron does allow having multiple datasets stored as different files at different places https://github.com/microsoft/Megatron-DeepSpeed/blob/1f640c00c115eee9cd8515db80f8c92a4c24e9ca/megatron/arguments.py#L700
