### ISSUE TITLE
The error in the calculation of the args.ffn_hidden_size for the swiglu

### ISSUE THREAD

**Issue by WenjinW** [microsoft/Megatron-DeepSpeed#184]
https://github.com/microsoft/Megatron-DeepSpeed/blob/ba79efc8bc39a68f38179f68792bad1f2f19199f/megatron/arguments.py#L271-L277

The computation in this calculation is different from the computation in the official LLama2, which results in a mismatch of parameter shapes when loading the official checkpoint.

**Comment by conglongli** [comment]
@LydiaXiaohongLi (https://github.com/microsoft/Megatron-DeepSpeed/pull/166) and @nrailgun (https://github.com/microsoft/Megatron-DeepSpeed/pull/177), could any of you confirm this?

If this is true, I think it's preferable to add a llama_swiglu arg so that the calculation only changes when using llama. If any of you could help test that and submit a PR, I'm happy to help review and merge. Thank you.

**Comment by LydiaXiaohongLi** [comment]
yes, I think there are slight deviations, for example, the official llama-13b, ffn_hidden_size is 13824, the above calculated one is 13568. the small deviation is just different ways to round off 8/3*hiddne_size to nearest multiple of 2^x.  
maybe we can change to follow existing as default calculation only **when ffn_hidden_size is not specified**, but if anyone requires different setup, they can just overwrite in ffn_hidden_size argument configuration? as in this case the difference is small, and no golden standard to setup, really depends on how much tp or some other considerations. what do you think?

**Comment by conglongli** [comment]
Thanks for the clarification @LydiaXiaohongLi . Due to the concern of backward compatibility, we would prefer to only switch this calculation when user specifically turns on a new flag (for example, a new args.llama_swiglu as I mentioned above). @WenjinW If that sounds good to you, feel free to create a PR.

**Comment by WenjinW** [comment]
Yes, that sounds great. I have created a PR(#191) to fix this issue.

**Comment by conglongli** [comment]
@WenjinW the PR needs some fixes, please take a look at my review comments.
