### ISSUE TITLE
Deepspeed version

### ISSUE THREAD

**Issue by Godricly** [microsoft/Megatron-DeepSpeed#234]
What is the deepspeed version used in this repo?
`sequence_data_parallel_group` is not found in the deepspeed 0.10.1 version.

https://github.com/microsoft/Megatron-DeepSpeed/blob/b5039dd7bb489ecd2a2cc8ed211d548273f2f6bf/pretrain_gpt.py#L39-L43

**Comment by binwang777** [comment]
![image](https://github.com/microsoft/Megatron-DeepSpeed/assets/32870325/25c5c4bb-e915-4c26-b256-d3c8a51d21d1)
I'm using deepspeed 0.9.5 and it's working!

**Comment by tohtana** [comment]
Hi all,
You need to use 0.10.3 or later to enable [DS-Ulysses](https://github.com/microsoft/DeepSpeed/tree/master/blogs/deepspeed-ulysses), but older versions of deepspeed should be compatible with the call of `mpu.get_sequence_data_parallel_group()` because the function is [defined in this repo](https://github.com/microsoft/Megatron-DeepSpeed/blob/c08e2cc2579cf7ef5ce6ad58453e76a5710b7b6b/megatron/core/parallel_state.py#L367).

I'm not sure why the reference to the function caused an error. It is good to know that the latest version of deepspeed solves the issue, but it would be helpful to solve the error with an old version if you could share more details.

**Comment by Godricly** [comment]
I updated both repos to the latest master, which works for me. So can I close this issue?

**Comment by tohtana** [comment]
@Godricly Thank you for the update!
Yes, you can close this issue. Please feel free to reopen if you encounter the same issue.
