### ISSUE TITLE
[REQUEST] Could you add a new release version tag to Megatron-Deepspeed？Thanks

### ISSUE THREAD

**Issue by hijeffwu** [microsoft/Megatron-DeepSpeed#366]
@tjruwase 
@jaredcasper
@lmcafee-nvidia

Could you add a new release version tag to Megatron-Deepspeed？Thanks

**Comment by mrwyattii** [comment]
Hi @hijeffwu we have not added version tags because there is a bit of complexity around the existing versioning from the main Megatron repo and handling versions of this forked repo (especially with respect to rebasing to get upstream changes). Could you help me understand the reason you want a release version tag? That could help guide how we go about this. Thanks!

**Comment by hijeffwu** [comment]
hi @mrwyattii  ,  the expectation for having a specific version is due to the fact that we're employing a megatron-deepspeed monkey-patch approach to support non-CUDA devices. For instance, we are implemented a megatron_deepspeed_plugin for GCU devices. Therefore, we hope to install a megatorn-deepspeed package via "pip install megatron_deepspeed==23.5" (for examples) and subsequently leverage this plugin to facilitate support for gcu devices.

examples:
pip2 insall megatron-deepspeed==23.5
pip3 install megatron-deepspeed_gcu (monkey patch for gcu )
